name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1.1.3
        with:
          buildozer_version: stable
          command: buildozer -v android debug

      - name: Create GitHub Release and Upload APK
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.${{ github.run_number }}
          name: "Pain Management APK Build"
          body: "Automated build from GitHub Actions"
          artifacts: "bin/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}

