name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to create releases

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker-based Buildozer environment
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            kivy/buildozer:stable \
            buildozer -v android debug

      - name: Upload APK to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.${{ github.run_number }}
          name: "Pain Management App Build"
          body: "Automatically built with GitHub Actions"
          artifacts: "bin/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
