name: Build Android APK

on:
  push:
    branches:
      - main  # Adjust if your default branch is named differently

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1.1.3
        with:
          buildozer_version: stable
          command: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: PainManagementApp
          path: bin/*.apk
